import { tachyonManifold } from "./tachyon-manifold";

describe("tachyonManifold", () => {
  it("counts the times the beam is split", () => {
    const input = `
    ..S..
    .....
    ..^..
    .....
    .^.^.
    .....
    `;
    const { splits } = tachyonManifold(input);
    expect(splits).toBe(3);
  });

  it("counts the times the beam is split - example", () => {
    const input = `
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............`;
    const { splits } = tachyonManifold(input);
    expect(splits).toBe(21);
  });

  it("counts the possible pathways a quantum tachyon can take - example", () => {
    const input = `
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............`;
    const { pathways } = tachyonManifold(input);
    expect(pathways).toBe(40);
  });

  it("counts the possible pathways a quantum tachyon can take", () => {
    const input = `
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............`;
    const { pathways } = tachyonManifold(input);
    expect(pathways).toBe(13);
  });
});
