import { TachyonManifold } from "./tachyon-manifold";

describe("tachyonManifold", () => {
  it("can be initialised", () => {
    const input = `
    ..S..
    .....
    ..^..
    .....
    .^.^.
    .....
    `;
    const manifold = new TachyonManifold(input);
    expect(manifold).not.toBeNull();
  });

  it("counts the times the beam is split", () => {
    const input = `
    ..S..
    .....
    ..^..
    .....
    .^.^.
    .....
    `;
    const manifold = new TachyonManifold(input);
    expect(manifold.countSplits()).toBe(3);
  });

  it("counts the times the beam is split - example", () => {
    const input = `
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............`;
    const manifold = new TachyonManifold(input);
    expect(manifold.countSplits()).toBe(21);
  });

  it("counts the possible pathways a quantum tachyon can take - example", () => {
    const input = `
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............`;
    const manifold = new TachyonManifold(input);
    expect(manifold.pathways).toBe(40);
  });

  it("counts the possible pathways a quantum tachyon can take", () => {
    const input = `
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............`;
    const manifold = new TachyonManifold(input);
    expect(manifold.pathways).toBe(13);
  });
});

// 1
// 1 1
// 1 2 1
// 1 3 3 1
// 1 4 3 3 1 1
